% -*-latex-*-
% Document name: /usr/local/lib/tex/bibtex/xampl.ltx
% Creator: Nelson H. F. Beebe [beebe@alfred.math.utah.edu]
% Creation Date: Mon Jun  8 08:42:49 1992

\documentstyle[]{article}

\author{A. U. Thor}

\date{}

\title{Bibliography Style: {\tt {abbrv}}}

\pagestyle{myheadings}

\markboth{Bibliography Style: {\tt {abbrv}}}{Bibliography Style: {\tt {abbrv}}}

\begin{document}

  \bibliographystyle{abbrv}

  \maketitle

  \nocite{*}

  \bibliography{xampl}

\end{document}